### ISSUE TITLE
How to disable the animation at navigationbar?

### ISSUE THREAD

**Issue by dos1in** [Interactive-Studio/TransitionableTab#2]
Hi, I have three ViewControllers and their color of navigationBar is different. 
So change the tab by TransitionableTab, the color of navigationBar can't change smoothly.
How to deal with that problem, Hope to get your help.

**Comment by ParkGwangBeom** [comment]
Thank you for reporting this issue. This issue will be fixed in the next version

**Comment by ParkGwangBeom** [comment]
@JChord Fixed in version 0.1.2

**Comment by dos1in** [comment]
@ParkGwangBeom Good job, It works for me:D.
