### ISSUE TITLE
pop back to root view controller while in navigation controller..

### ISSUE THREAD

**Issue by prakashmaharjan** [Interactive-Studio/TransitionableTab#3]
The animation is really nice. 
Is there a way to pop back to root view controller instead of animation, when user taps on same tab icon while user have already navigated to inside view on tab?

**Comment by ParkGwangBeom** [comment]
@PrakashMaharjan Fixed in version 0.1.2

**Comment by prakashmaharjan** [comment]
Thank you for the fix..
